export const message={
    unAuthorizedMessage: "You are not authorized to access this resource.",
    FieldsRequiredMessage:"All fields are required.",
    userAlreadyExistsMessage:"User already exists with this email.",
    userCreatedMessage:"User created successfully, please verify your email.",
    userVerifiedMessage:"User verified successfully.",
    idNotFoundMessage:"ID not found.",
    userNotFoundMessage:"User not found.",
    userAlreadyVerifiedMessage:"User is already verified.",
    otpSendMessage:"otp send successfully",
    otpVerifiedMessage:"OTP verified successfully.",
    otpAttemptsExceedMessage:"OTP attempts exceeded, please try again later.",
    otpNotFoundMessage:"OTP not found, please provide a valid OTP.",
    otpExpireMessage:"OTP has expired, please request a new OTP.",
    userVerifiedMessage:"User verified successfully.",
    loginSuccessfulMessage:"Login successful.",
    userNotVerifiedMessage:"User is not verified.",
    resetPasswordSuccessfulMessage:"Password reset successful, please login with your new password.",
    resetPasswordExpireMessage:"Reset password link has expired, please request a new one.",
    resetPasswordAttemptsExceedMessage:"Reset password attempts exceeded, please try again later.",
    invalidOtpMessage:"Invalid OTP, please try again.",
    passwordChangeMessage:"Password changed successfully.",
    logoutMessage:"Logged out successfully.",
    userProfileFoundMessage:"User profile found successfully.",
    userProfileUpdatedMessage:"User profile updated successfully.",
    loginLockedMessage:"Login Locked please try again later.",
    usersFoundMessage:"Users found successfully.",
    usersNotFoundMessage:"Users not found.",
    userDeletedMessage:"User deleted successfully.",
    unauthorizedUserMessage:"Unauthorized user, you do not have permission to perform this action.",
    complaintCreatedMessage: "Complaint created successfully",
	complaintsFetchedMessage: "Complaints fetched successfully",
	complaintFetchedMessage: "Complaint fetched successfully",
	complaintNotFoundMessage: "Complaint not found",
	complaintUpdatedMessage: "Complaint updated successfully",
	complaintDeletedMessage: "Complaint deleted successfully",
}